import = ["~/dotfiles/alacritty/os/current.toml"]

[env]
TERM = "xterm-256color"

[selection]
save_to_clipboard = true

[window]
padding.x = 20
padding.y = 20

decorations = "ButtonLess"
opacity = 0.92
blur = true

[font]
size = 14.0
