#!/usr/bin/env bash
# Build the Windows Alacritty config: one flat file in %APPDATA%.
#
# On Windows, Alacritty is a Windows program and resolves `~` against the
# Windows home (C:\Users\<name>), not the WSL one. The base config's
# `import` list points at `~/dotfiles/alacritty/...`, so copying the base over
# as-is leaves both imports dangling — the RU layout table and the per-OS
# copy/paste bindings simply never load, silently. Alacritty has no runtime
# conditionals and no second search path to fix that with, so the three files
# are flattened here instead: base without its `import` block, then one
# `[keyboard]` section holding the RU twins followed by the OS profile's
# bindings.
#
# Order inside that array is the order of the base's `import` list — RU layout
# first, OS profile second — because Alacritty lets a later binding win over an
# earlier one for the same key, and platform beats shared.
#
# Idempotent: re-run after any change to the three sources. The result carries
# a GENERATED header; a file without one is treated as hand-written and backed
# up once before being replaced.
set -euo pipefail

dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
base="$dir/alacritty.toml"
layout="$dir/ru-layout.toml"

# Which profile: the same three-way test as select-device.sh, because the
# gesture depends on the OS delivering the keys, and here that is Windows
# talking to WSL — the wsl profile. Overridable by argument for the rare case
# of building for another machine from this one.
if [ $# -gt 0 ]; then
  profile="$dir/os/$1.toml"
else
  profile="$dir/os/wsl.toml"
fi
[ -f "$profile" ] || { echo "no such profile: $profile" >&2; exit 1; }

appdata=$(cmd.exe /c echo %APPDATA% 2>/dev/null | tr -d '\r')
[ -n "$appdata" ] || { echo "cannot read %APPDATA% — is this WSL with interop on?" >&2; exit 1; }
out_dir="$(wslpath -u "$appdata")/alacritty"
out="$out_dir/alacritty.toml"

# Everything except the `import` block: the imports are what this script
# replaces.
strip_import() {
  awk '
    /^import[[:space:]]*=[[:space:]]*\[/ { skip = 1; next }
    skip && /^\]/                        { skip = 0; next }
    skip                                 { next }
                                         { print }
  ' "$1"
}

# The entries between `bindings = [` and its closing bracket, with a trailing
# comma added where the source did not need one: the last entry of a file stops
# being last once another file's entries follow it.
bindings_of() {
  awk '
    /^bindings[[:space:]]*=[[:space:]]*\[/ { inside = 1; next }
    inside && /^\]/                        { inside = 0; next }
    inside                                 { print }
  ' "$1" | sed -E 's/\}([[:space:]]*)(#.*)?$/},\1\2/'
}

mkdir -p "$out_dir"

if [ -f "$out" ] && ! head -1 "$out" | grep -q 'GENERATED'; then
  cp -a "$out" "$out.bak"
  echo "· existing hand-written config saved as $out.bak"
fi

tmp=$(mktemp)
trap 'rm -f "$tmp"' EXIT
{
  echo "# GENERATED by dotfiles/alacritty/build-windows.sh — do not edit here."
  echo "# Sources: alacritty.toml, ru-layout.toml, os/$(basename "$profile")."
  echo "# Edit those and re-run the script; this file is overwritten."
  echo
  strip_import "$base"
  echo
  echo "# ── ru-layout.toml, then os/$(basename "$profile") ──"
  echo "[keyboard]"
  echo "bindings = ["
  bindings_of "$layout"
  bindings_of "$profile"
  echo "]"
} > "$tmp"

mv "$tmp" "$out"
trap - EXIT
echo "· %APPDATA%\\alacritty\\alacritty.toml <- base + ru-layout + os/$(basename "$profile")"
